### ISSUE TITLE
Import controller could not be resolved

### ISSUE THREAD

**Issue by adilbonzi** [IuAyala/Self-Driving-Cars-Course#1]
Hello, 

after downloading the code file and running the webots file, I received the error on VS code, stating 

- import "controller" could not be resolved. 
- Import "vehicle" could not be resolved.

I am aware that I am missing the function file. 
Where can I locate this file?

![image](https://user-images.githubusercontent.com/25233555/163706033-bdfe0c89-bfb8-46f3-b07e-dbf4a8b7dcc5.png)

**Comment by IuAyala** [comment]
Thanks for raising this, I will have a look in a week, as I'm away right
now.

Kind regards
Iu

**Comment by adilbonzi** [comment]
Thanks Lu. 
Will look forward to your feedback. 

Kind regards,
Adil

**Comment by IuAyala** [comment]
Hey abilbonzi,

Both the "controller" and "vehicle" files are part of the Webots Python API (the simulator).
In my machine (Linux) those are found in: "/usr/local/webots/lib/controller/python39/vehicle.py"

You can find the instructions to install it in the README.md -- [link](https://github.com/IuAyala/Self-Driving-Cars-Course)
Alternatively you can see the official documentation [here](https://cyberbotics.com/doc/guide/installation-procedure#installation-on-linux).

Let me know if it doesn't work after doing that.

Regards,
Iu

**Comment by IuAyala** [comment]
I haven't heard from you in a while, I will close the issue, let me know if there is any other issue.

I hope that you are enjoying the hands-on exercises.
